### ISSUE TITLE
Would it be possible to make sources a glob or allow multiple paths?

### ISSUE THREAD

**Issue by jblotus** [scheb/tombstone-analyzer#2]
It would be handy if i could give multiple paths to the "source-dir"  argument

**Comment by scheb** [comment]
At first I was like "sure, why not", but there's in fact a problem with multiple source paths. That single source path is used to make the file paths, in which the tombstones are located, relative paths, so they can be matched later. This is important e.g. if you have a deployment strategy, which generates a new folder for every release and you just switch a symlink. So the source path ensures that you get the same relative paths independent of the project's root path, on different machines or even different environments. Now the issue with multiple source paths is, after making it a relativ path, you can no longer tell which source path the file was originally in and therefore matching the paths may produce false positives.

If your question is about efficiency, e.g. you want to skip the vendor directory in the code analysis because that codes doesn't matter, the we should probably introduce include/exclude patterns as command line options.

**Comment by scheb** [comment]
Latest version of the analyzer allows to specify the directories (multiple ones) and file name patterns to be analyzed. Nevertheless, there must be a single root directory to act as the root of all relative path names, otherwise the path name mapping doesn't work.
